#!/usr/bin/env node
// Bundles the sh-icon-genie browser build into docs/genie-bundle.js so the
// gallery can generate icons client-side. The name keeps it clear of
// docs/icon-genie.js, which is the hand-written <icon-genie> web component.
//
// The gallery is a single static page with no bundler, and a strict page like it
// cannot import from a CDN, so the dependency is vendored at build time into one
// self-contained ES module. Regenerated by `npm run build:icons`.
//
// What the gallery needs from it is the safety gate: when a user generates with
// their own API key, or pastes a response from their own AI chat, the model's
// output reaches the page without passing through the hosted proxy. The page must
// run the same path validation and SVG sanitization the proxy would have run.
import { build } from "esbuild";
import path from "node:path";
import { DOCS_DIR } from "./utils.js";

const outfile = path.join(DOCS_DIR, "genie-bundle.js");

const result = await build({
  entryPoints: ["sh-icon-genie"],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: ["es2020"],
  minify: true,
  sourcemap: false,
  legalComments: "inline",
  outfile,
  metafile: true,
});

for (const warning of result.warnings) {
  console.warn(`  ${warning.text}`);
}
const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
console.log(`Bundled sh-icon-genie -> docs/genie-bundle.js (${(bytes / 1024).toFixed(1)}KB)`);
