#!/usr/bin/env node
// Writes the shared header into each page's HTML, so it paints with the body.
//
// The bar used to exist only at runtime: a page shipped `<header
// data-site-header></header>` and lib/header.js filled it once three module
// files had been fetched and evaluated. The body is markup in the file and
// paints immediately; the header could not, so it arrived visibly late on every
// navigation between pages.
//
// Generating it keeps the single source of truth that the runtime build was
// there to provide. docs/lib/header-markup.js holds the template, this script
// stamps it into the HTML, and lib/header.js uses the same function as a
// fallback for a page that has not been generated. A renamed tool is still one
// edit, in one file.
//
// Idempotent: it replaces whatever is between the header tags, so running it
// twice writes the same thing. The generated block is not hand-editable — an
// edit inside it is overwritten on the next build, which is what the marker
// comment in the output says.
import fs from "node:fs";
import path from "node:path";
import { DOCS_DIR } from "./utils.js";
import { headerBarHtml, HEADER_PAGES } from "../docs/lib/header-markup.js";

// Matches the mount point whether it is still empty or already filled.
const HEADER_RE = /(<header data-site-header>)([\s\S]*?)(<\/header>)/;

const NOTE =
  "\n      <!-- Generated by scripts/build-header.js from docs/lib/header-markup.js.\n" +
  "           Do not edit here; edit the template and rebuild. -->\n      ";

let written = 0;
let skipped = 0;

for (const [file, options] of Object.entries(HEADER_PAGES)) {
  const full = path.join(DOCS_DIR, file);
  if (!fs.existsSync(full)) {
    console.warn(`  ${file}: not found, skipped`);
    skipped++;
    continue;
  }

  const before = fs.readFileSync(full, "utf8");
  if (!HEADER_RE.test(before)) {
    // A page that opted out, or whose mount point was renamed. Saying so beats
    // silently leaving one page with a late header.
    console.warn(`  ${file}: no <header data-site-header> to fill, skipped`);
    skipped++;
    continue;
  }

  const bar = headerBarHtml(options);
  const after = before.replace(HEADER_RE, (_, open, __, close) => `${open}${NOTE}${bar}\n    ${close}`);

  if (after === before) {
    console.log(`  ${file}: already current`);
    continue;
  }
  fs.writeFileSync(full, after);
  console.log(`  ${file}: header written`);
  written++;
}

console.log(
  `Header written into ${written} page${written === 1 ? "" : "s"}` +
    (skipped ? ` (${skipped} skipped)` : "") +
    `.`
);
